#!/usr/bin/env python3
"""
Example: Generate minimal Dockerfile for any execution script.

This demonstrates how to use script_manifests.json to create
optimized Docker images with only required dependencies.

Usage:
    python3 execution/example_minimal_docker.py write_cold_emails
    python3 execution/example_minimal_docker.py calendly_meeting_prep --output /tmp/Dockerfile
"""

import argparse
import json
import sys
from pathlib import Path


def load_manifests():
    """Load script manifests."""
    manifest_path = Path(__file__).parent / 'script_manifests.json'

    if not manifest_path.exists():
        print(f"❌ Error: Manifest file not found")
        print("   Run: python3 execution/analyze_script_dependencies.py")
        sys.exit(1)

    with open(manifest_path) as f:
        return json.load(f)


def load_requirements():
    """Load version mapping from requirements.txt."""
    requirements_path = Path(__file__).parent.parent / 'requirements.txt'
    version_map = {}

    if requirements_path.exists():
        with open(requirements_path) as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith('#'):
                    continue

                if '>=' in line:
                    pkg, ver = line.split('>=', 1)
                    version_map[pkg.strip()] = f">={ver.strip()}"
                elif '==' in line:
                    pkg, ver = line.split('==', 1)
                    version_map[pkg.strip()] = f"=={ver.strip()}"

    return version_map


def generate_dockerfile(script_name, manifest, version_map):
    """Generate minimal Dockerfile for a script."""
    # Build requirements list with versions
    requirements = []
    for pkg in manifest['packages']:
        version = version_map.get(pkg, "")
        requirements.append(f"{pkg}{version}")

    # Generate Dockerfile
    dockerfile = f"""# Minimal Docker image for {manifest['script']}
# Generated by example_minimal_docker.py
# This image contains ONLY the dependencies needed for this script

FROM python:3.11-slim

WORKDIR /app

# Install only required packages
RUN pip install --no-cache-dir \\
    {' \\\n    '.join(requirements) if requirements else '# No external packages required'}

# Copy only the script
COPY execution/{manifest['script']} .

# Required environment variables:
{chr(10).join(f'# - {var}' for var in manifest['env_vars']) if manifest['env_vars'] else '# No environment variables required'}

# Set them when running:
# docker run -e VAR1=value1 -e VAR2=value2 ...

CMD ["python", "{manifest['script']}"]
"""

    return dockerfile


def generate_docker_compose(script_name, manifest):
    """Generate docker-compose.yml for a script."""
    env_vars = "\n".join(f"      - {var}=${{{{var}}}}" for var in manifest['env_vars'])

    compose = f"""# docker-compose.yml for {manifest['script']}
# Generated by example_minimal_docker.py

version: '3.8'

services:
  {script_name.replace('_', '-')}:
    build:
      context: .
      dockerfile: Dockerfile.{script_name}
    environment:
{env_vars if env_vars else '      # No environment variables required'}
    volumes:
      - ./.tmp:/app/.tmp
    restart: unless-stopped

# To run:
# 1. Set environment variables in .env file
# 2. docker-compose up -d
"""

    return compose


def generate_railway_config(script_name, manifest):
    """Generate Railway nixpacks.toml config."""
    # Build install command
    install_cmd = " ".join(manifest['packages']) if manifest['packages'] else "# No packages"

    config = f"""# nixpacks.toml for {manifest['script']}
# Generated by example_minimal_docker.py
# Deploy: railway up

[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["pip install {install_cmd}"]

[start]
cmd = "python execution/{manifest['script']}"

# Required environment variables (set in Railway dashboard):
{chr(10).join(f'# {var}' for var in manifest['env_vars']) if manifest['env_vars'] else '# No environment variables required'}
"""

    return config


def main():
    parser = argparse.ArgumentParser(description='Generate minimal Docker config for a script')
    parser.add_argument('script', help='Script name (without .py)')
    parser.add_argument('--output', help='Output Dockerfile path (default: stdout)')
    parser.add_argument('--docker-compose', action='store_true', help='Also generate docker-compose.yml')
    parser.add_argument('--railway', action='store_true', help='Generate Railway nixpacks.toml')
    args = parser.parse_args()

    # Load data
    manifests = load_manifests()
    version_map = load_requirements()

    # Get manifest
    script_key = args.script.replace('.py', '')

    if script_key not in manifests:
        print(f"❌ Script not found: {args.script}")
        print(f"\nAvailable scripts: {len(manifests)}")
        for key in sorted(manifests.keys())[:5]:
            print(f"  - {key}")
        print("  ...")
        sys.exit(1)

    manifest = manifests[script_key]

    # Generate Dockerfile
    dockerfile = generate_dockerfile(script_key, manifest, version_map)

    # Output
    if args.output:
        output_path = Path(args.output)
        output_path.write_text(dockerfile)
        print(f"✅ Dockerfile written to: {output_path}")

        # Show image size estimate
        base_size = 150  # python:3.11-slim is ~150MB
        pkg_size = len(manifest['packages']) * 15  # Rough estimate: 15MB per package
        total_size = base_size + pkg_size

        print(f"\n📦 Estimated image size: ~{total_size}MB")
        print(f"   Base image (python:3.11-slim): ~{base_size}MB")
        print(f"   Dependencies ({len(manifest['packages'])} packages): ~{pkg_size}MB")

        if manifest['stdlib_only']:
            print(f"\n✨ This is a stdlib-only script!")
            print(f"   Image will be minimal (~{base_size}MB)")
    else:
        print(dockerfile)

    # Docker Compose
    if args.docker_compose:
        compose = generate_docker_compose(script_key, manifest)
        compose_path = Path(f"docker-compose.{script_key}.yml")
        compose_path.write_text(compose)
        print(f"\n✅ docker-compose.yml written to: {compose_path}")

    # Railway config
    if args.railway:
        railway = generate_railway_config(script_key, manifest)
        railway_path = Path(f"nixpacks.{script_key}.toml")
        railway_path.write_text(railway)
        print(f"\n✅ Railway config written to: {railway_path}")

    # Show usage instructions
    if args.output:
        print(f"\n📝 Next steps:")
        print(f"   1. Review the Dockerfile: cat {args.output}")
        print(f"   2. Build the image: docker build -t {script_key} -f {args.output} .")

        if manifest['env_vars']:
            print(f"   3. Set environment variables:")
            for var in manifest['env_vars'][:3]:
                print(f"      export {var}='your-value'")
            if len(manifest['env_vars']) > 3:
                print(f"      ... and {len(manifest['env_vars']) - 3} more")

        print(f"   4. Run: docker run -it {script_key}")


if __name__ == '__main__':
    main()
