#!/usr/bin/env python3
"""
Railway Web Service: calendly-meeting-prep
Auto-generated by deploy_to_railway.py
"""

import os
import json
import subprocess
import sys
from pathlib import Path
from datetime import datetime
from flask import Flask, request, jsonify

app = Flask(__name__)

@app.route("/health")
def health():
    return jsonify({"status": "healthy", "service": "calendly-meeting-prep", "timestamp": datetime.utcnow().isoformat()})

@app.route("/webhook", methods=["POST"])
def webhook():
    payload = request.get_json(silent=True) or {}
    input_data = payload.get("data", payload)

    args = []
    for key, value in input_data.items():
        if value is not None and value != "":
            args.extend([f"--{key}", str(value)])

    script = Path(__file__).parent / "calendly_meeting_prep.py"
    if not script.exists():
        return jsonify({"error": "Script not found"}), 500

    try:
        result = subprocess.run(
            [sys.executable, str(script)] + args,
            capture_output=True, text=True, timeout=600,
            env={**os.environ, "PYTHONPATH": str(Path(__file__).parent.parent)},
        )
        return jsonify({
            "status": "success" if result.returncode == 0 else "error",
            "stdout": result.stdout[-2000:] if result.stdout else "",
            "stderr": result.stderr[-1000:] if result.stderr else "",
        })
    except subprocess.TimeoutExpired:
        return jsonify({"error": "Script timed out"}), 504
    except Exception as e:
        return jsonify({"error": str(e)}), 500

if __name__ == "__main__":
    port = int(os.getenv("PORT", 8080))
    app.run(host="0.0.0.0", port=port)
