#!/usr/bin/env python3
"""
Test Doc Generator - Railway Cron Job

Runs every 2 hours via Railway cron schedule.
Creates a test Google Doc and sends it to Slack.

Environment Variables Required:
- GOOGLE_OAUTH_TOKEN_PICKLE: Base64 encoded token.pickle for Google OAuth
- SLACK_WEBHOOK_URL: For Slack notifications
"""

import base64
import json
import os
import pickle
import sys
from datetime import datetime
from pathlib import Path

import requests

# Try to load Google libraries
try:
    from google.oauth2.credentials import Credentials
    from google.auth.transport.requests import Request
    from googleapiclient.discovery import build
except ImportError:
    print("ERROR: Google API libraries not installed")
    print("Install with: pip install google-api-python-client google-auth google-auth-oauthlib")
    sys.exit(1)

# Configuration - requires environment variables (no hardcoded fallbacks)
SLACK_WEBHOOK_URL = os.getenv("SLACK_WEBHOOK_URL")
GOOGLE_OAUTH_TOKEN_PICKLE = os.getenv("GOOGLE_OAUTH_TOKEN_PICKLE")

if not SLACK_WEBHOOK_URL:
    print("ERROR: SLACK_WEBHOOK_URL environment variable not set")
    sys.exit(1)
if not GOOGLE_OAUTH_TOKEN_PICKLE:
    print("ERROR: GOOGLE_OAUTH_TOKEN_PICKLE environment variable not set")
    sys.exit(1)

SCOPES = [
    "https://www.googleapis.com/auth/documents",
    "https://www.googleapis.com/auth/drive"
]


def get_google_credentials():
    """Get Google credentials from base64-encoded token.pickle in environment."""
    if not GOOGLE_OAUTH_TOKEN_PICKLE:
        print("ERROR: GOOGLE_OAUTH_TOKEN_PICKLE not set")
        return None

    try:
        # Decode base64 token
        token_bytes = base64.b64decode(GOOGLE_OAUTH_TOKEN_PICKLE)
        creds = pickle.loads(token_bytes)

        # Refresh if expired
        if creds and creds.expired and creds.refresh_token:
            print("Refreshing expired token...")
            creds.refresh(Request())
            # Note: In Railway, we can't update the env var, but the refreshed creds work for this session

        if creds and creds.valid:
            print("Google credentials loaded successfully")
            return creds
        else:
            print("ERROR: Credentials invalid after refresh")
            return None

    except Exception as e:
        print(f"ERROR loading Google credentials: {e}")
        return None


def create_test_google_doc() -> dict:
    """Create a test Google Doc with timestamp."""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S UTC")
    date_str = datetime.now().strftime("%Y-%m-%d")

    print(f"\n{'='*60}")
    print("STEP 1: Creating Test Google Doc")
    print(f"{'='*60}")

    creds = get_google_credentials()
    if not creds:
        return {"success": False, "error": "No Google credentials"}

    try:
        # Build services
        docs_service = build("docs", "v1", credentials=creds)

        # Create document
        title = f"Test Doc - {date_str}"
        doc = docs_service.documents().create(body={"title": title}).execute()
        doc_id = doc.get("documentId")

        print(f"Created document: {doc_id}")

        # Generate test content
        content = f"""Test Document Generated by AIAA Workflow

Generated: {timestamp}
Workflow: Test Doc Generator
Platform: Railway Cron (every 2 hours)

This is a test document automatically generated by your AIAA Agentic OS workflow system.

What This Proves:
- Google Docs API integration is working
- OAuth credentials are valid
- Railway cron scheduling is active
- Slack notifications are configured

Status: SUCCESS

Next scheduled run: In 2 hours

Generated by AIAA Agentic OS
"""

        # Insert content
        requests_batch = [{
            "insertText": {
                "location": {"index": 1},
                "text": content
            }
        }]

        docs_service.documents().batchUpdate(
            documentId=doc_id,
            body={"requests": requests_batch}
        ).execute()

        # Apply some formatting (make title bold)
        formatting_requests = [
            {
                "updateParagraphStyle": {
                    "range": {"startIndex": 1, "endIndex": 45},
                    "paragraphStyle": {"namedStyleType": "HEADING_1"},
                    "fields": "namedStyleType"
                }
            }
        ]

        docs_service.documents().batchUpdate(
            documentId=doc_id,
            body={"requests": formatting_requests}
        ).execute()

        doc_url = f"https://docs.google.com/document/d/{doc_id}/edit"

        print(f"Document URL: {doc_url}")

        return {
            "success": True,
            "doc_id": doc_id,
            "doc_url": doc_url,
            "title": title,
            "timestamp": timestamp
        }

    except Exception as e:
        print(f"ERROR creating Google Doc: {e}")
        import traceback
        traceback.print_exc()
        return {"success": False, "error": str(e)}


def send_slack_notification(doc_result: dict) -> dict:
    """Send Slack notification with the doc link."""
    print(f"\n{'='*60}")
    print("STEP 2: Sending Slack Notification")
    print(f"{'='*60}")

    if not SLACK_WEBHOOK_URL:
        print("SLACK_WEBHOOK_URL not configured - skipping notification")
        return {"sent": False, "reason": "No webhook URL"}

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S UTC")

    if doc_result.get("success"):
        message = {
            "text": "Test Doc Generated",
            "blocks": [
                {
                    "type": "header",
                    "text": {
                        "type": "plain_text",
                        "text": "Test Doc Generated"
                    }
                },
                {
                    "type": "section",
                    "text": {
                        "type": "mrkdwn",
                        "text": f"*Your test Google Doc is ready!*\n\n<{doc_result['doc_url']}|Open Document>"
                    }
                },
                {
                    "type": "section",
                    "fields": [
                        {
                            "type": "mrkdwn",
                            "text": f"*Title:*\n{doc_result['title']}"
                        },
                        {
                            "type": "mrkdwn",
                            "text": f"*Status:*\nSuccess"
                        }
                    ]
                },
                {
                    "type": "context",
                    "elements": [
                        {
                            "type": "mrkdwn",
                            "text": f"Generated on {timestamp} | Workflow runs every 2 hours"
                        }
                    ]
                }
            ]
        }
    else:
        message = {
            "text": "Test Doc Generator Failed",
            "blocks": [
                {
                    "type": "header",
                    "text": {
                        "type": "plain_text",
                        "text": "Test Doc Generator Failed"
                    }
                },
                {
                    "type": "section",
                    "text": {
                        "type": "mrkdwn",
                        "text": f"*Error:* {doc_result.get('error', 'Unknown error')}"
                    }
                },
                {
                    "type": "context",
                    "elements": [
                        {
                            "type": "mrkdwn",
                            "text": f"Failed on {timestamp}"
                        }
                    ]
                }
            ]
        }

    try:
        response = requests.post(SLACK_WEBHOOK_URL, json=message, timeout=30)
        if response.status_code == 200:
            print("Slack notification sent!")
            return {"sent": True}
        else:
            print(f"Slack notification failed: {response.status_code}")
            return {"sent": False, "status_code": response.status_code}
    except Exception as e:
        print(f"Error sending Slack notification: {e}")
        return {"sent": False, "error": str(e)}


def main():
    """Main execution flow."""
    print("=" * 60)
    print("TEST DOC GENERATOR")
    print("Railway Cron Job - Runs Every 2 Hours")
    print("=" * 60)
    print(f"Started: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")

    # Validate environment
    missing_vars = []
    if not GOOGLE_OAUTH_TOKEN_PICKLE:
        missing_vars.append("GOOGLE_OAUTH_TOKEN_PICKLE")
    if not SLACK_WEBHOOK_URL:
        missing_vars.append("SLACK_WEBHOOK_URL (optional)")

    if "GOOGLE_OAUTH_TOKEN_PICKLE" in missing_vars:
        print(f"\nERROR: Missing required environment variable: GOOGLE_OAUTH_TOKEN_PICKLE")
        print("This should be a base64-encoded token.pickle file")
        return 1

    try:
        # Step 1: Create Google Doc
        doc_result = create_test_google_doc()

        # Step 2: Send Slack notification
        slack_result = send_slack_notification(doc_result)

        print(f"\n{'='*60}")
        print("WORKFLOW COMPLETE")
        print(f"{'='*60}")
        print(f"Doc Created: {doc_result.get('success', False)}")
        print(f"Slack Sent: {slack_result.get('sent', False)}")
        print(f"Completed: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")

        return 0 if doc_result.get("success") else 1

    except Exception as e:
        print(f"\nERROR: {e}")
        import traceback
        traceback.print_exc()

        # Try to send error notification
        if SLACK_WEBHOOK_URL:
            try:
                requests.post(SLACK_WEBHOOK_URL, json={
                    "text": f"Test Doc Generator failed: {str(e)[:100]}"
                }, timeout=30)
            except:
                pass

        return 1


if __name__ == "__main__":
    sys.exit(main())
