#!/usr/bin/env python3
"""
Hook 107: delivery_receipt_generator.py (PostToolUse on Bash)
Purpose: Generate delivery receipts after successful deliveries.
Logic: After delivery scripts run (create_google_doc, send_slack), generate a
receipt in .tmp/receipts/ with: what was delivered, when, to whom, delivery method.

Protocol:
  - PostToolUse: prints JSON to stdout {"decision": "ALLOW"}
  - Supports --status and --reset CLI flags
"""

import json
import sys
import re
import os
from pathlib import Path
from datetime import datetime

STATE_DIR = Path(".tmp/hooks")
STATE_FILE = STATE_DIR / "delivery_receipts.json"
RECEIPTS_DIR = Path(".tmp/receipts")

# Delivery script patterns
DELIVERY_SCRIPTS = {
    "create_google_doc.py": "Google Docs",
    "send_slack_notification.py": "Slack",
    "send_email.py": "Email",
    "upload_to_drive.py": "Google Drive",
    "publish_to_wordpress.py": "WordPress",
    "deploy_": "Railway Deployment",
    "share_": "Shared Link",
}


def load_state():
    try:
        if STATE_FILE.exists():
            return json.loads(STATE_FILE.read_text())
    except (json.JSONDecodeError, OSError):
        pass
    return {
        "receipts": [],
        "total_deliveries": 0,
        "by_method": {},
        "by_client": {}
    }


def save_state(state):
    STATE_DIR.mkdir(parents=True, exist_ok=True)
    STATE_FILE.write_text(json.dumps(state, indent=2))


def detect_delivery_method(command):
    """Detect delivery method from command."""
    for script, method in DELIVERY_SCRIPTS.items():
        if script in command:
            return method
    return None


def extract_delivery_details(command):
    """Extract details about what's being delivered."""
    details = {}

    # File being delivered
    file_match = re.search(r'--file[=\s]+["\']?([^"\']+)["\']?', command)
    if file_match:
        details["file"] = file_match.group(1).strip()

    # Title
    title_match = re.search(r'--title[=\s]+["\']?([^"\']+)["\']?', command)
    if title_match:
        details["title"] = title_match.group(1).strip()

    # Message content
    msg_match = re.search(r'--message[=\s]+["\']?([^"\']+)["\']?', command)
    if msg_match:
        details["message"] = msg_match.group(1).strip()[:100]

    # Channel/recipient
    channel_match = re.search(r'--channel[=\s]+["\']?([^"\']+)["\']?', command)
    if channel_match:
        details["channel"] = channel_match.group(1).strip()

    # Client
    client_match = re.search(r'--client[=\s]+["\']?([^"\']+)["\']?', command)
    if client_match:
        details["client"] = client_match.group(1).strip()

    return details


def generate_receipt(receipt_data):
    """Generate a receipt markdown file."""
    RECEIPTS_DIR.mkdir(parents=True, exist_ok=True)

    receipt_id = receipt_data.get("receipt_id", "unknown")
    timestamp = receipt_data.get("timestamp", datetime.now().isoformat())
    method = receipt_data.get("method", "Unknown")
    details = receipt_data.get("details", {})

    receipt_content = f"""# Delivery Receipt

- **Receipt ID:** {receipt_id}
- **Timestamp:** {timestamp}
- **Delivery Method:** {method}
"""

    if details.get("file"):
        receipt_content += f"- **File:** {details['file']}\n"
    if details.get("title"):
        receipt_content += f"- **Title:** {details['title']}\n"
    if details.get("client"):
        receipt_content += f"- **Client:** {details['client']}\n"
    if details.get("channel"):
        receipt_content += f"- **Channel:** {details['channel']}\n"
    if details.get("message"):
        receipt_content += f"- **Message:** {details['message']}\n"

    receipt_content += f"\n---\n*Generated by delivery_receipt_generator hook*\n"

    receipt_file = RECEIPTS_DIR / f"receipt_{receipt_id}.md"
    try:
        receipt_file.write_text(receipt_content)
        return str(receipt_file)
    except OSError:
        return None


def show_status():
    state = load_state()
    receipts = state.get("receipts", [])
    by_method = state.get("by_method", {})
    by_client = state.get("by_client", {})

    print("=== Delivery Receipt Generator ===")
    print(f"Total deliveries: {state.get('total_deliveries', 0)}")
    print(f"Receipt directory: {RECEIPTS_DIR}")

    if by_method:
        print("\nDeliveries by method:")
        for method, count in sorted(by_method.items(), key=lambda x: x[1], reverse=True):
            print(f"  {method}: {count}")

    if by_client:
        print("\nDeliveries by client:")
        for client, count in sorted(by_client.items(), key=lambda x: x[1], reverse=True):
            print(f"  {client}: {count}")

    if receipts:
        print(f"\nRecent receipts (last {min(10, len(receipts))}):")
        for r in receipts[-10:]:
            rid = r.get("receipt_id", "?")
            method = r.get("method", "?")
            ts = r.get("timestamp", "?")[:19]
            title = r.get("details", {}).get("title", r.get("details", {}).get("file", "?"))
            print(f"  [{rid}] {method}: {title} ({ts})")

    # Check actual receipt files
    if RECEIPTS_DIR.exists():
        receipt_files = list(RECEIPTS_DIR.glob("receipt_*.md"))
        print(f"\nReceipt files on disk: {len(receipt_files)}")

    sys.exit(0)


def reset_state():
    if STATE_FILE.exists():
        STATE_FILE.unlink()
    print("Delivery receipt generator state reset.")
    sys.exit(0)


def main():
    if "--status" in sys.argv:
        show_status()
    if "--reset" in sys.argv:
        reset_state()

    try:
        data = json.loads(sys.stdin.read())
    except (json.JSONDecodeError, EOFError):
        print(json.dumps({"decision": "ALLOW"}))
        return

    tool_name = data.get("tool_name", "")
    tool_input = data.get("tool_input", {})
    tool_result = data.get("tool_result", "")

    if tool_name not in ("Bash", "bash"):
        print(json.dumps({"decision": "ALLOW"}))
        return

    command = tool_input.get("command", "")
    method = detect_delivery_method(command)

    if not method:
        print(json.dumps({"decision": "ALLOW"}))
        return

    # Check if delivery was successful (no error indicators in result)
    result_str = str(tool_result).lower() if tool_result else ""
    error_indicators = ["error", "traceback", "failed", "exception", "errno"]
    if any(indicator in result_str for indicator in error_indicators):
        # Delivery failed - don't generate receipt
        print(json.dumps({"decision": "ALLOW"}))
        return

    state = load_state()
    now = datetime.now().isoformat()
    state["total_deliveries"] = state.get("total_deliveries", 0) + 1

    # Generate receipt ID
    receipt_id = f"{now[:10].replace('-', '')}_{state['total_deliveries']:04d}"

    details = extract_delivery_details(command)

    receipt_data = {
        "receipt_id": receipt_id,
        "timestamp": now,
        "method": method,
        "details": details,
        "command": command[:200]
    }

    # Generate receipt file
    receipt_path = generate_receipt(receipt_data)
    if receipt_path:
        receipt_data["receipt_file"] = receipt_path

    # Update stats
    state["receipts"] = state.get("receipts", [])
    state["receipts"].append(receipt_data)
    state["receipts"] = state["receipts"][-200:]

    by_method = state.get("by_method", {})
    by_method[method] = by_method.get(method, 0) + 1
    state["by_method"] = by_method

    client = details.get("client", "unattributed")
    by_client = state.get("by_client", {})
    by_client[client] = by_client.get(client, 0) + 1
    state["by_client"] = by_client

    save_state(state)
    print(json.dumps({"decision": "ALLOW"}))


if __name__ == "__main__":
    main()
